

const products = [
  {
    id: 1,
    title: "Booster Brave F1",
    beforePrice: null,
    afterPrice: '$490.00',
    img:'/assets/p1.jpg' ,
    category: "Electric Scooter",
  },
  {
    id: 2,
    title: "GoodLock J10",
    beforePrice: null,
    afterPrice: '$95.00',
    img: "/assets/p2.jpg",
    category: "Accessories",
  },
  {
    id: 3,
    title: "Hammer Scooter Lock",
    beforePrice: null,
    afterPrice: "$75.00",
    img: "/assets/p3.jpg",
    category: "Accessories",
  },
  {
    id: 4,
    title: "Libero X150",
    beforePrice: null,
    afterPrice: "$750.00",
   img: "/assets/p4.jpg",
    category: "Electric Scooter",
  },
  {
    id: 5,
    title: "Libero X250",
    beforePrice: null,
    afterPrice: "$750.00",
   img: "/assets/p5.jpg",
    category: "Electric Scooter",
  },

  {
    id: 6,
    title: "Libero X350",
    beforePrice: "$875.00",
    afterPrice: '$799.00',
    img: "/assets/p6.jpg",
    category: "Electric Scooter",
  },
  {
    id: 7,
    title: "MAX3 Scooter Lock",
    beforePrice: null,
    afterPrice: '$90.00',
    img: "/assets/p7.jpg",
    category: "Accessories",
  },
  {
    id: 8,
    title: "North Booster 1",
    beforePrice: null,
    afterPrice: '$725.00',
   img: "/assets/p8.jpg",
    category: "Electric Scooter",
  },
  {
    id: 9,
    title: "North D Booster 2000",
    beforePrice: null,
    afterPrice:'$890.00',
   img: "/assets/p9.jpg",
    category: "Electric Scooter",
  },
  {
    id: 10,
    title: "Practico PRO 500",
    beforePrice: null,
    afterPrice: "$699.00",
   img: "/assets/p10.jpg",
    category: "Electric Scooter",
  },

  {
    id: 11,
    title: "Practico S2 Exclusive",
    beforePrice: "$750.00",
    afterPrice: "$600.00",
  img: "/assets/p11.jpg",
    category: "Electric Scooter",
  },
  {
    id: 12,
    title: "Practico Z50 Exclusive",
    beforePrice:null,
    afterPrice: "$750.00",
  img: "/assets/p12.jpg",
    category: "Electric Scooter",
  },
  {
    id: 13,
    title: "SilverPath C1",
    beforePrice: null,
    afterPrice: "$725.00",
    img: "/assets/p13.jpg",
    category: "Electric Scooter",
  },
  {
    id: 14,
    title: "SilverPath MAX1",
    beforePrice: null,
    afterPrice: "$699.00",
   img: "/assets/p14.jpg",
    category: "Electric Scooter",
  },
  {
    id: 15,
    title: "SilverPath MAX2",
    beforePrice: null,
    afterPrice: "$575.00",
    img: "/assets/p15.jpg",
    category: "Electric Scooter",
  },

  {
    id: 16,
    title: "U-Lock Force",
    beforePrice: null,
    afterPrice: '$99.00',
   img: "/assets/p16.jpg",
    category: "Accessories",
  },
  {
    id: 17,
    title: "U-Lock Force MAX",
    beforePrice: '$90.00',
    afterPrice: '$75.00',
   img: "/assets/p17.jpg",
    category: "Accessories",
  },
  {
    id: 18,
    title: "Unbeatable Lock 100",
    beforePrice: '$80.00',
    afterPrice: '$69.00',
  img: "/assets/p18.jpg",
    category: "Accessories",
  },

];

export default products;
